name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test-release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Setup Github
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
      - name: Use Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "npm"
      - run: npm ci
      - name: Run Release Script
        run: |
          npm run release
          git push --follow-tags origin main
